version: "3.8"

services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    volumes:
      - .:/app  